port: 5000

title: 云南大学信息技术中心 - 师生服务
email: 65031141@ynu.edu.cn
description: >- 
  运维服务部（65031141）
  周一至周日：8:30～11:30；14:00～16:50；19:00～21:00
baseurl: "/" 
url: "https://oms.thiswind.org" 

# Build settings
markdown: kramdown
theme: minima
