- name: 绑定一卡通APP手机号
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5afe3659f9e8ef12024a838f

- name: 重置上网账号密码
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0cbe28e7d0143a005810a4
  
- name: 申请电子邮箱
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0cc2a7f8dc526f6d93b9e8
  
- name: 解锁邮箱&重置电子邮箱密码
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0e410933174065ee357d39
    
- name: 邮箱扩容
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0cc9ce2c7b1a6f6733d5bd
  
- name: 统一身份认证绑定手机号（在校师生）
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0e4413b49386633741c1f6
  
- name: 统一身份认证绑定手机号（外聘人员）
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0e47df54138a7e02de04e2
  
- name: 校园网络问题
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0e4b40ebd6f565fe338b7e
