- name: 绑定一卡通APP手机号
  description: 在您正确线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5afe3659f9e8ef12024a838f

- name: 重置上网账号密码
  description: 在您正确线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0cbe28e7d0143a005810a4
  
- name: 申请电子邮箱
  description: 在您正确线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0cc2a7f8dc526f6d93b9e8
