- name: 一卡通APP重新绑定手机号
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5afe3659f9e8ef12024a838f
  label: 提交申请

- name: 重置上网账号（VPN账号）密码
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0cbe28e7d0143a005810a4
  label: 提交申请

- name: 硕士研究生申请VPN账号（疫情期间面向硕士研究生临时开放）
  description: 信息技术中心已经为我校所有全日制学术硕士和专业硕士临时开通了VPN账号，无需另行申请。
  url: http://65031141.ynu.edu.cn/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/2019/09/03/%E4%BA%91%E5%8D%97%E5%A4%A7%E5%AD%A6VPN%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B.html
  label: 点击查看VPN使用教程
  
- name: 申请电子邮箱
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0cc2a7f8dc526f6d93b9e8
  label: 提交申请
  
- name: 解锁邮箱&重置电子邮箱密码
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0e410933174065ee357d39
  label: 提交申请
    
- name: 邮箱扩容
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0cc9ce2c7b1a6f6733d5bd
  label: 提交申请
  
- name: 校园网络问题
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5b0e4b40ebd6f565fe338b7e
  label: 提交申请
  
- name: 校内应用系统使用异常
  description: 您正确在线提交申请之后，请注意接收信息技术中心运维服务部的来电或短信，我们会在工作时间为您处理并和您联系
  url: https://jiandaoyun.com/f/5bbc0dbacd8038436f786fc1
  label: 提交申请

- name: 意见和建议
  description: 如果您对我们的服务有什么意见和建议
  url: https://link.jiandaoyun.com/f/5c9b04f13a8450248195bd22
  label: 点击提交

- name: 统一身份认证绑定手机号&电子邮箱（在校师生）
  description: 若您已经忘记统一身份认证密码，并且没有绑定手机号或电子邮箱，则点击此处提交申请。在您正确提交申请之后请耐心等待，在收到我们绑定成功的回复之后，您可以在统一身份认证登录页面点击“忘记密码”来通过手机号找回密码。
  url: https://jiandaoyun.com/f/5b0e4413b49386633741c1f6
  label: 提交申请
  
- name: 统一身份认证绑定手机号&电子邮箱（外聘人员）
  description: 若您已经忘记统一身份认证密码，并且没有绑定手机号或电子邮箱，则点击此处提交申请。在您正确提交申请之后请耐心等待，在收到我们绑定成功的回复之后，您可以在统一身份认证登录页面点击“忘记密码”来通过手机号找回密码。
  url: https://jiandaoyun.com/f/5b0e47df54138a7e02de04e2
  label: 提交申请

- name: 下载一卡通APP
  url: http://www.ynu.edu.cn/info/1005/4679.htm
  label: 查看：转载自学校官网

- name: 校历
  url: https://www.ynu.edu.cn/0000.jpg
  label: 查看
  
- name: 校车时刻表
  url: http://www.hqjt.ynu.edu.cn/schoolbus/675.jhtml
  label: 查看：转载自后勤集团网站

- name: 统一身份认证自助绑定手机号服务
  description: 若你当前没有忘记统一身份认证密码，可通过此链接自助绑定手机号，今后忘记密码可用手机验证码找回。
  url: https://ids.ynu.edu.cn/authserver/
  label: 点击进入
